name: Check if Reference Docs need to be regenerated

on:
  pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Generate reference docs
        run: npm run docs
      - name: Check for diff
        run: git diff --exit-code -- 'docs/reference***.md'

